### ISSUE TITLE
Could we have a release done and a pip package added to pypi?

### ISSUE THREAD

**Issue by pcm32** [ISA-tools/isatools-core#4]
Hi @djcomlab!

I submitted a request for a Galaxy wheel to be created for isa-rwal, however they are asking first for a release for pip. Could you help us with that part? Release should be based on the current dev branch that we are currently using for the Galaxt datatype. Thanks!

Here is the pull for wheel on Galaxy:
https://github.com/galaxyproject/starforge/pull/197

**Comment by djcomlab** [comment]
Hi @pcm32, yep sure, sorry have been on leave the last couple of weeks. Should get this done in the next day or so.

**Comment by djcomlab** [comment]
@pcm32 Please try out using `isa-rwval` from PyPI. If you need a fixed version use `isa-rwval==0.10.0`.

**Comment by djcomlab** [comment]
Released, so closing. Galaxy guys seem to be OK with using it right now.
